# Fuck you Disyer. Stealing my fucking paypal. GET FUCKED: toontown.suit.SuitGlobals
from panda3d.core import Fog, VBase4
from toontown.suit import SuitDNA
SCALE_INDEX = 0
HAND_COLOR_INDEX = 1
HEADS_INDEX = 2
HEAD_TEXTURE_INDEX = 3
HEIGHT_INDEX = 4
WEAKNESS_INDEX = 5
aSize = 6.06
bSize = 5.29
cSize = 4.14
ColdCallerHead = VBase4(0.25, 0.35, 1.0, 1.0)
suitProperties = {'f': (4.0 / cSize,
       SuitDNA.corpPolyColor,
       ['flunky', 'glasses'],
       '',
       4.88,
       [(2, 0)]),
 'p': (3.35 / bSize,
       SuitDNA.corpPolyColor,
       ['pencilpusher'],
       '',
       5.0,
       [(5, 1)]),
 'ym': (4.125 / aSize,
        SuitDNA.corpPolyColor,
        ['yesman'],
        '',
        5.28,
        [(4, 1)]),
 'mm': (2.5 / cSize,
        SuitDNA.corpPolyColor,
        ['micromanager'],
        '',
        3.25,
        [(6, 2)]),
 'ds': (4.5 / bSize,
        VBase4(0.8, 0.7, 0.7, 1.0),
        ['downsizer', 'hatjp187187'],
        '',
        6.08,
        [(1, 4)]),
 'hh': (6.5 / aSize,
        SuitDNA.corpPolyColor,
        ['headhunter'],
        '',
        7.45,
        [(6, 5)]),
 'cr': (6.75 / cSize,
        VBase4(0.85, 0.55, 0.55, 1.0),
        ['flunky'],
        'corporate-raider.jpg',
        8.23,
        [(6, 6)]),
 'tbc': (7.0 / aSize,
         VBase4(0.75, 0.95, 0.75, 1.0),
         ['bigcheese'],
         '',
         9.34,
         [(4, 4)]),
 'bf': (4.0 / cSize,
        SuitDNA.legalPolyColor,
        ['tightwad'],
        'bottom-feeder.jpg',
        4.81,
        [(1, 0)]),
 'b': (4.375 / bSize,
       VBase4(0.95, 0.95, 1.0, 1.0),
       ['movershaker'],
       'blood-sucker.jpg',
       6.17,
       [(4, 0)]),
 'dt': (4.25 / aSize,
        SuitDNA.legalPolyColor,
        ['twoface'],
        'double-talker.jpg',
        5.63,
        [(1, 1)]),
 'ac': (4.35 / bSize,
        SuitDNA.legalPolyColor,
        ['ambulancechaser'],
        '',
        6.39,
        [(3, 3)]),
 'bs': (4.5 / aSize,
        SuitDNA.legalPolyColor,
        ['backstabber'],
        '',
        6.71,
        [(6, 3)]),
 'sd': (5.65 / bSize,
        VBase4(0.8, 0.9, 0.7, 1.0),
        ['spindoctor', 'scopejp187187', 'bandjp187187'],
        '',
        7.9,
        [(3, 4)]),
 'le': (7.125 / aSize,
        VBase4(0.25, 0.25, 0.5, 1.0),
        ['legaleagle'],
        '',
        8.27,
        [(5, 5)]),
 'bw': (7.0 / aSize,
        SuitDNA.legalPolyColor,
        ['bigwig'],
        '',
        8.69,
        [(1, 5)]),
 'sc': (3.6 / cSize,
        SuitDNA.moneyPolyColor,
        ['coldcaller'],
        '',
        4.77,
        [(6, 0)]),
 'pp': (3.55 / aSize,
        VBase4(1.0, 0.5, 0.6, 1.0),
        ['pennypincher'],
        '',
        5.26,
        [(2, 2)]),
 'tw': (4.5 / cSize,
        SuitDNA.moneyPolyColor,
        ['tightwad'],
        'tightwad.jpg',
        5.41,
        [(6, 1)]),
 'bc': (4.4 / bSize,
        SuitDNA.moneyPolyColor,
        ['beancounter'],
        '',
        5.95,
        [(1, 3)]),
 'nc': (5.25 / aSize,
        SuitDNA.moneyPolyColor,
        ['numbercruncher'],
        '',
        7.22,
        [(2, 3)]),
 'mb': (5.3 / cSize,
        SuitDNA.moneyPolyColor,
        ['moneybags'],
        '',
        6.97,
        [(6, 4)]),
 'ls': (6.5 / bSize,
        VBase4(0.5, 0.85, 0.75, 1.0),
        ['loanshark'],
        '',
        8.58,
        [(5, 6)]),
 'rb': (7.0 / aSize,
        SuitDNA.moneyPolyColor,
        ['yesman'],
        'robber-baron.jpg',
        8.95,
        [(2, 4)]),
 'cc': (3.5 / cSize,
        VBase4(0.55, 0.65, 1.0, 1.0),
        ['coldcaller'],
        '',
        4.63,
        [(5, 0)]),
 'tm': (3.75 / bSize,
        SuitDNA.salesPolyColor,
        ['telemarketer'],
        '',
        5.24,
        [(3, 1)]),
 'nd': (4.35 / aSize,
        SuitDNA.salesPolyColor,
        ['numbercruncher'],
        'name-dropper.jpg',
        5.98,
        [(1, 2)]),
 'gh': (4.75 / cSize,
        SuitDNA.salesPolyColor,
        ['gladhander'],
        '',
        6.4,
        [(4, 3)]),
 'ms': (4.75 / bSize,
        SuitDNA.salesPolyColor,
        ['movershaker'],
        '',
        6.7,
        [(5, 4)]),
 'tf': (5.25 / aSize,
        SuitDNA.salesPolyColor,
        ['twoface'],
        '',
        6.95,
        [(2, 5)]),
 'm': (5.75 / aSize,
       SuitDNA.salesPolyColor,
       ['twoface'],
       'mingler.jpg',
       7.61,
       [(4, 5)]),
 'mh': (7.0 / aSize,
        SuitDNA.salesPolyColor,
        ['yesman'],
        '',
        8.95,
        [(4, 6)]),
 'sk': (4.2 / cSize,
        SuitDNA.techPolyColor,
        ['flunky'],
        'scriptkiddie.jpg',
        5.12,
        [(3, 0)]),
 'cm': (4.5 / cSize,
        SuitDNA.techPolyColor,
        ['gladhander'],
        'code_monkey.jpg',
        6.06,
        [(2, 1)]),
 'vp': (4.8 / aSize,
        SuitDNA.techPolyColor,
        ['yesman'],
        'voodoo_programmer.jpg',
        6.13,
        [(4, 2)]),
 'db': (4.9 / cSize,
        SuitDNA.techPolyColor,
        ['shotgun'],
        '',
        7.5,
        [(5, 3)]),
 'kc': (4.81 / bSize,
        SuitDNA.techPolyColor,
        ['beancounter'],
        'suits_tech.jpg',
        6.5,
        [(5, 2)]),
 'ss': (5.25 / aSize,
        SuitDNA.techPolyColor,
        ['numbercruncher'],
        'software_simian.jpg',
        6.95,
        [(3, 5)]),
 'iw': (5.8 / bSize,
        SuitDNA.techPolyColor,
        ['movershaker'],
        'wizard-installer.jpg',
        7.68,
        [(2, 6)]),
 'ru': (7.0 / aSize,
        SuitDNA.techPolyColor,
        ['telemarketer'],
        'rootuser.jpg',
        8.95,
        [(3, 6)])}
WeaknessToSuit = {}
for name, properties in suitProperties.iteritems():
    for gag in properties[WEAKNESS_INDEX]:
        if gag not in WeaknessToSuit:
            WeaknessToSuit[gag] = [name]
        else:
            WeaknessToSuit[gag].append(name)