# Fuck you Disyer. Stealing my fucking paypal. GET FUCKED: toontown.building.FADoorCodes
from toontown.toonbase import TTLocalizer
UNLOCKED = 0
CLASS_IN_SESSION = 1
BUILDING_TAKEOVER = 2
SB_DISGUISE_INCOMPLETE = 3
CB_DISGUISE_INCOMPLETE = 4
LB_DISGUISE_INCOMPLETE = 5
BB_DISGUISE_INCOMPLETE = 6
TB_DISGUISE_INCOMPLETE = 7
reasonDict = {UNLOCKED: TTLocalizer.FADoorCodes_UNLOCKED,
 CLASS_IN_SESSION: TTLocalizer.FADoorCodes_CLASS_IN_SESSION,
 BUILDING_TAKEOVER: TTLocalizer.FADoorCodes_BUILDING_TAKEOVER,
 SB_DISGUISE_INCOMPLETE: TTLocalizer.FADoorCodes_SB_DISGUISE_INCOMPLETE,
 CB_DISGUISE_INCOMPLETE: TTLocalizer.FADoorCodes_CB_DISGUISE_INCOMPLETE,
 LB_DISGUISE_INCOMPLETE: TTLocalizer.FADoorCodes_LB_DISGUISE_INCOMPLETE,
 BB_DISGUISE_INCOMPLETE: TTLocalizer.FADoorCodes_BB_DISGUISE_INCOMPLETE,
 TB_DISGUISE_INCOMPLETE: TTLocalizer.FADoorCodes_TB_DISGUISE_INCOMPLETE}